version: '3'

services:
    mysql:
        container_name: project-mysql
        image: mysql:5.7
        volumes:
            - ./.data/mysql:/var/lib/mysql
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        expose:
            - 3306
        ports:
          - 23306:3306

    phpmyadmin:
        container_name: project-mysql-admin
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        expose:
            - 80
        ports:
            - 9080:80

    mongo:
        container_name: short-link-mongo
        build: ./server-setting/mongodb
        volumes:
            - ./.data/mongo:/data/db
        ports:
            - 37017:27017
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGODB_USERNAME: ${MONGODB_USERNAME}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_DB: ${MONGODB_DB}

    mongo-express:
        container_name: short-link-mongo-admin
        image: mongo-express
        restart: always
        expose:
            - 8081
        ports:
            - 9081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'

    redis:
        container_name: project-redis
        image: redis:3.0.6
        container_name: cache
        expose:
          - 6379
        ports:
            - 6379:6379

    php:
        container_name: project-php
        links:
              - mysql
              - mongo
              - redis
        build:
            context: ./server-setting/php
            args:
                TIMEZONE: Europe/Kiev
        volumes:
            - .data/mail:/media/mail
            - ./server-setting/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ${SYMFONY_VOLUME_PATH}:/var/www/symfony:nocopy
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGODB_USERNAME: ${MONGODB_USERNAME}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_DATABASE: ${MONGODB_DATABASE}

    nginx:
        container_name: project-nginx
        build: ./server-setting/nginx
        links:
            - php
        ports:
            - 8999:80
        volumes:
            - ${SYMFONY_VOLUME_PATH}:/var/www/symfony:nocopy

    composer:
        container_name: project-composer
        image: composer
        restart: 'no'
        command: composer install --ignore-platform-reqs
        volumes:
            - ${SYMFONY_VOLUME_PATH}:/app

volumes:
    app-sync:
        external: true